[package]
name = "envdb"
version = "0.1.5"
edition = "2021"

[dependencies]
clap = { version = "4.0.23", features = ["cargo"] }
exitcode = "1.1.2"
tempfile = "3.5.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
